version: '2.18'
services:
  db:
    image: postgres:15
    container_name: CFT
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  CFT:
    image: cft_image
    build:
      context: .
    container_name: cft_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
    command: ["/CFT/docker/app.sh"]
    ports:
      - 7777:8000
